6.7. Работа со строкой запроса
htmlacademy-php1/2006761-yeticave-14 pull request #10
Opened 2022-04-16 22:27 UTC by oneg1g

2022-04-18 04:43 UTC, olegmifle requested changes

2022-04-18 04:43 UTC, olegmifle commented on functions.php
> +function checkExistDbVal($checking_item) {
Нет типизации
Переменные должны быть в camelCase стиле

2022-04-18 04:43 UTC, olegmifle commented on index.php
> +                   ORDER BY l.created_at DESC';
Вынеси это и другие запросы в отдельные функции и унеси в functions. Пора наводить чистоту :)

2022-04-18 04:43 UTC, olegmifle commented on lot.php
> +$lot_id = intval($_GET['ID']);
Переменные должны быть в camelCase стиле.

2022-04-18 04:43 UTC, olegmifle commented on lot.php
> +        $ArrCategories = mysqli_fetch_all($result, MYSQLI_ASSOC);
Переменные должны быть в camelCase стиле.

2022-04-18 04:43 UTC, olegmifle commented on lot.php
> +    print('Error MySQL: ' . $error);
Ты можешь это сделать один раз в init - либо подключился, либо выбросил ошибку и завершил сценарий (die)

2022-04-18 04:43 UTC, olegmifle commented on lot.php
> +        $ArrCategories = mysqli_fetch_all($result, MYSQLI_ASSOC);
Унеси это в функцию

2022-04-18 04:43 UTC, olegmifle commented on lot.php
> +    }
Унеси это в функцию
Вместо конкатенации запроса с переменной используй 
mysqli_prepare -> mysqli_stmt_bind_param -> mysqli_stmt_execute -> mysqli_stmt_get_result -> mysqli_fetch_assoc
Т.е. сначала готовишь запрос, потом биндишь к нему переменные, выполняешь и забираешь результаты. Так запрос будет защищён

2022-04-18 04:43 UTC, olegmifle commented on lot.php
> +    }
Тут то же самое

2022-04-18 04:43 UTC, olegmifle commented on lot.php
> +        'ArrBidUser' => $ArrBidUser,
Оформляй плз в едином стиле. Тут у тебя с большой буквы, ниже у тебя snake_case.

2022-04-18 04:43 UTC, olegmifle commented on templates/main.php
> +                    <a class="text-link" href="/lot.php?ID=<?=$value['id']?>"><?=htmlspecialchars($value['lot_name']);?></a>
А имя лота тебе зачем?

2022-04-19 11:07 UTC, oneg1g commented on lot.php
> +    }
<img width="722" alt="1" src="https://user-images.githubusercontent.com/82041934/163990130-983c2ccd-aed3-4271-8888-7f9de4b917d0.png">
<img width="950" alt="2" src="https://user-images.githubusercontent.com/82041934/163990145-ac56b244-43d2-499f-8574-57a8e4678810.png">
почему bool передается вместо mysqli_stmt? Что не так сделал?

2022-04-20 05:10 UTC, olegmifle requested changes

2022-04-20 05:10 UTC, olegmifle commented on functions.php
> +function checkExistDbVal(array $checkingItem) {
Нет возвращаемого типа.
Название функции не понятное. Что она делать должна?

2022-04-20 05:10 UTC, olegmifle commented on functions.php
> +        if ($arr===NULL) {
```suggestion
        if ($arr === null) {
```

2022-04-20 05:10 UTC, olegmifle commented on functions.php
> +        $arr = mysqli_fetch_assoc($result);
$arr не очень удачное название переменной, оно не отражает содержимого.

2022-04-20 05:10 UTC, olegmifle commented on functions.php
> +            die();
Это не входит в зону ответственности этой функции. Функция должна вернуть конкретный результат, а не делать доп. действия.

2022-04-20 09:08 UTC, olegmifle approved these changes

2022-04-20 09:08 UTC, merged