Написал условие на показ имени пользователя
htmlacademy-php1/2006761-yeticave-14 pull request #2
Opened 2022-03-28 17:13 UTC by oneg1g

2022-03-29 05:23 UTC, olegmifle requested changes

2022-03-29 05:23 UTC, olegmifle commented on index.php
> +        <?php if($is_auth==1): ?>
Используй строгое сравнение, т.к. при таком будет неявное приведение типов.

2022-03-29 05:23 UTC, olegmifle commented on index.php
> +</div>
Следи плз за отступами, что бы отступы отображали вложенность -- так проще читать код.

2022-03-29 16:19 UTC, oneg1g commented on index.php
> +</div>
Понял

2022-03-30 03:58 UTC, olegmifle approved these changes

2022-03-30 03:58 UTC, merged